### ISSUE TITLE
Lift System

### ISSUE THREAD

**Issue by MarkDannemiller** [FHS-Robotics/FRC-VSCode-Team5866#8]
Description:
We need to create a subsystem to control our elevator.  This should be simple enough using just one motor but if we implement some limit switches then we will be able to read when the elevator has reached the bottom or the top.

Done:
To be done, we need a subsystem called LiftSystem, and a command that uses the joystick to drive the elevator up and down and eventually uses two limit switches to read using the Digital IO pins whether or not we've reached an upper or lower limit so that it will stop.  We will implement autonomous code later but if someone could get to work on just the one motor and running it using the joystick then that's a good start.

**Comment by JadenSeale23** [comment]
Sounds good I can get started on that
